# Generated by Django 4.2.4 on 2023-09-12 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
    ]
